### ISSUE TITLE
Error building with  '@semantic-release', 'babel-runtime', 'webpack-core' and '@bahmutov' modules

### ISSUE THREAD

**Issue by ayxos** [krux/prescribe#216]
In order to create a PR, I am trying to build the lib via `npm run build`, but i get the following error with '@semantic-release', 'babel-runtime', 'webpack-core' and '@bahmutov' modules. What am i doing wrong? 

Thanks

```javascript
[16:19:09] Requiring external module babel-register
node_modules/nan
resolve failed:  { Error: Cannot find module '@semantic-release'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.requireRelative.resolve (/Users/marco/projects/prescribe/node_modules/require-relative/index.js:30:17)
    at resolve (/Users/marco/projects/prescribe/node_modules/modify-babel-preset/lib/serialize.js:26:26)
    at findAndRemove (/Users/marco/projects/prescribe/node_modules/modify-babel-preset/lib/serialize.js:83:11)
    at /Users/marco/projects/prescribe/node_modules/modify-babel-preset/lib/serialize.js:126:13
    at Array.map (native)
    at loadPreset (/Users/marco/projects/prescribe/node_modules/modify-babel-preset/lib/serialize.js:118:29)
    at module.exports (/Users/marco/projects/prescribe/node_modules/modify-babel-preset/index.js:95:19)
    at Object.<anonymous> (/Users/marco/projects/prescribe/node_modules/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/marco/projects/prescribe/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at /Users/marco/projects/prescribe/node_modules/babel-core/lib/transformation/file/options/option-manager.js:302:17
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/marco/projects/prescribe/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/Users/marco/projects/prescribe/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/Users/marco/projects/prescribe/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14) code: 'MODULE_NOT_FOUND' } @semantic-release
resolve failed:  { Error: Cannot find module 'babel-runtime'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.requireRelative.resolve (/Users/marco/projects/prescribe/node_modules/require-relative/index.js:30:17)
    at resolve (/Users/marco/projects/prescribe/node_modules/modify-babel-preset/lib/serialize.js:26:26)
    at findAndRemove (/Users/marco/projects/prescribe/node_modules/modify-babel-preset/lib/serialize.js:83:11)
    at /Users/marco/projects/prescribe/node_modules/modify-babel-preset/lib/serialize.js:126:13
    at Array.map (native)
    at loadPreset (/Users/marco/projects/prescribe/node_modules/modify-babel-preset/lib/serialize.js:118:29)
    at module.exports (/Users/marco/projects/prescribe/node_modules/modify-babel-preset/index.js:95:19)
    at Object.<anonymous> (/Users/marco/projects/prescribe/node_modules/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/marco/projects/prescribe/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at /Users/marco/projects/prescribe/node_modules/babel-core/lib/transformation/file/options/option-manager.js:302:17
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/marco/projects/prescribe/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/Users/marco/projects/prescribe/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/Users/marco/projects/prescribe/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14) code: 'MODULE_NOT_FOUND' } babel-runtime
resolve failed:  { Error: Cannot find module 'webpack-core'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.requireRelative.resolve (/Users/marco/projects/prescribe/node_modules/require-relative/index.js:30:17)
    at resolve (/Users/marco/projects/prescribe/node_modules/modify-babel-preset/lib/serialize.js:26:26)
    at findAndRemove (/Users/marco/projects/prescribe/node_modules/modify-babel-preset/lib/serialize.js:83:11)
    at /Users/marco/projects/prescribe/node_modules/modify-babel-preset/lib/serialize.js:126:13
    at Array.map (native)
    at loadPreset (/Users/marco/projects/prescribe/node_modules/modify-babel-preset/lib/serialize.js:118:29)
    at module.exports (/Users/marco/projects/prescribe/node_modules/modify-babel-preset/index.js:95:19)
    at Object.<anonymous> (/Users/marco/projects/prescribe/node_modules/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/marco/projects/prescribe/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at /Users/marco/projects/prescribe/node_modules/babel-core/lib/transformation/file/options/option-manager.js:302:17
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/marco/projects/prescribe/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/Users/marco/projects/prescribe/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/Users/marco/projects/prescribe/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14) code: 'MODULE_NOT_FOUND' } webpack-core
resolve failed:  { Error: Cannot find module '@bahmutov'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.requireRelative.resolve (/Users/marco/projects/prescribe/node_modules/require-relative/index.js:30:17)
    at resolve (/Users/marco/projects/prescribe/node_modules/modify-babel-preset/lib/serialize.js:26:26)
    at findAndRemove (/Users/marco/projects/prescribe/node_modules/modify-babel-preset/lib/serialize.js:83:11)
    at /Users/marco/projects/prescribe/node_modules/modify-babel-preset/lib/serialize.js:126:13
    at Array.map (native)
    at loadPreset (/Users/marco/projects/prescribe/node_modules/modify-babel-preset/lib/serialize.js:118:29)
    at module.exports (/Users/marco/projects/prescribe/node_modules/modify-babel-preset/index.js:95:19)
    at Object.<anonymous> (/Users/marco/projects/prescribe/node_modules/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/marco/projects/prescribe/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at /Users/marco/projects/prescribe/node_modules/babel-core/lib/transformation/file/options/option-manager.js:302:17
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/marco/projects/prescribe/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/Users/marco/projects/prescribe/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/Users/marco/projects/prescribe/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14) code: 'MODULE_NOT_FOUND' } @bahmutov
semantic-release ERR! post Command "build" not recognized. Use either "pre" or "post"
```

**Comment by ayxos** [comment]
any updates?

**Comment by ayxos** [comment]
There is no .babelrc file in the repo (or is on .gitignore) so babel is not working.

Pls add a `.babelrc` with the following:

```
{
	"presets": [
		"es2015"
	]
}
```
